version: "1.0"
info:
  model: int-scaffold
packages:
- name: GitprojectTestProject
  gitServerName: githubSanthosh
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.gitprojecttest.integrations:A
  packages:
  - name: GitprojectTestProject
    version: "1.0"
- serviceName: pub.date:calculateDateDifference
  packages:
  - name: WmPublic
    version: 11.1.0.0.1136
